### PR TITLE
Fix .NET Core and .NET 5 support

### LINKED ISSUE #38: Package doesn't appear to work under .NET Core or .NET 5
I've created a new `netcoreapp3.1` WinForms app and added a package reference to the latest version of the package.

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="unvell.D2DLib" Version="1.2.2" />
  </ItemGroup>

</Project>
```

NuGet restore completes succesfully. It doesn't appear to have added any managed assembly references to the compilation, as I see error: 

> error CS0246: The type or namespace name 'unvell' could not be found (are you missing a using directive or an assembly reference?)

Looking in the `obj/project.assets.json` file I see:

```json
      "unvell.D2DLib/1.2.2": {
        "type": "package",
        "build": {
          "build/unvell.D2DLib.targets": {}
        }
      },
```

The `.targets` file is picked up. I see the linked `d2dlib32.dll` in the project tree.

image

If I change `<TargetFramework>` to `net4.8`, the compilation error goes away. The assets file now shows:

```json
      "unvell.D2DLib/1.2.2": {
        "type": "package",
        "compile": {
          "lib/net20/d2dlibexport.dll": {},
          "lib/net20/d2dwinform.dll": {}
        },
        "runtime": {
          "lib/net20/d2dlibexport.dll": {},
          "lib/net20/d2dwinform.dll": {}
        },
        "build": {
          "build/unvell.D2DLib.targets": {}
        }
      },
```

For some reason, NuGet is excluding the `compile` and `runtime` items when targeting `netcoreapp3.1` and `net5.0-windows`. My guess is the `.nuspec` file is at fault.

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #38, follows #39.

This PR fixes creation of the package for .NET Core and .NET 5 users, maintaining .NET Framework support.

It converts the projects from legacy csproj to newer SDK-style projects, which enable several new features such as native multi-targeting and NuGet pack from the project without a .nuspec file.

In future, to create a new version of the package:

1. Update the single `<Version>` element in `Directory.Build.props`. This controls the assembly and package version in a single place.
2. Pack the `D2DWinForm` project in VS (or via `dotnet pack`).

I've also enabled deterministic builds and SourceLink. Consumers of the package can now step into the library's code, and Visual Studio will download the source from GitHub directly.

A second `.snupkg` file is created alongside the `.nupkg` file, which will be uploaded to nuget.org automatically via `nuget.exe push foo.nupkg`. Users can download this when debug symbols are needed. The format of these symbols is portable across runtimes/frameworks.

The package icon is now embedded in the `.nupkg` file, rather than downloaded from github.com.

The package license is now an SPDX expression (`"MIT"`) rather than an embedded file.

I added an .editorconfig to avoid breaking code conventions in the editor (i.e. accidentally converting leading tabs to spaces).

See individual commit messages for more details.

### CODE REVIEW

**Comment by jingwood** [comment]
@drewnoakes Thanks so much! I need a little time to learn the changes about this. I will merge it.

**Comment by drewnoakes** [comment]
@jingwood sure, no problem. Take your time. I wanted to use this in a .NET 5 application, and with the changes in this PR was able to do so using a local package file. So I am unblocked for now, though of course I'd rather use a public package.

I'm happy to answer any questions you may have.

**Comment by jingwood** [comment]
@drewnoakes Thanks! The project config looks very cool and professional, it resolved my early questions such as how to package a native DLL. 

I am going to publish a new package with these latest changes.
Should I publish two packages for 32bit and 64bit target platform? if you have any ideas please let me know!

**Comment by drewnoakes** [comment]
@jingwood I'm glad to hear the changes work for you.

I don't think you need to create two packages. It is possible to support both platforms in a single NuGet package. We will need more changes here though. I'm curious to learn how to do that, so I'll take a look.

**Comment by drewnoakes** [comment]
Hmm, this seems more difficult than I hoped it would be.

See:

- https://github.com/NuGet/Home/issues/9369
- https://github.com/NuGet/docs.microsoft.com-nuget/issues/2070

It may be easier to produce two packages.

**Comment by jingwood** [comment]
@drewnoakes Thank you very much!

**Pull request merged**
