### PR TITLE
Initial support for line segment start/end caps

### PR DESCRIPTION
**Pull request by drewnoakes**
Relates to #55

D2D supports various line caps. This commit exposes those to users of the API so that values other than "flat" can be specified.

There are other draw methods for which this feature could be enabled (such as poly lines) that are not covered here.

This commit adds optional parameters to public API which is a breaking binary change, but a non-breaking source change.

### CODE REVIEW

**Comment by jingwood** [comment]
Added a test / demo for line cap drawing
image

**Comment by jingwood** [comment]
@drewnoakes Thanks very much!

**Comment by drewnoakes** [comment]
Thanks. The test looks great too.

**Comment by drewnoakes** [comment]
@jingwood any chance of a new package? I'd like to consume this feature. It's not super urgent for me, but would be nice. I see there are 31 commits since the last release.

**Comment by jingwood** [comment]
@drewnoakes Thanks for the suggestion! The new packages of v1.3.1 have been released now.

**Comment by drewnoakes** [comment]
@jingwood wow, thanks for the fast release! Appreciate all your work on this library.

**Pull request merged**
