### PR TITLE
Public sign assemblies

### PR DESCRIPTION
**Pull request by drewnoakes**
This enables [public signing](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/security#publicsign) for the assemblies in the package.

From that document:

> Developers use public sign for open-source projects.

This enables other strong-named assemblies to utilise this library.

---

It also bumps the copyright year and version. @jingwood if you're happy with this, could we get a package out? I'm blocked on needing strong naming for a project I want to use this in. Thanks! Alternatively you can give me publish permissions. My NuGet user ID is 'drewnoakes'.

### CODE REVIEW

**Comment by jingwood** [comment]
resolves the issue #84

**Comment by jingwood** [comment]
@drewnoakes Thank you very much! I have invited you as the collaborator of the repository and NuGet package. Thanks all the contributions to this library so far.

**Comment by jingwood** [comment]
@drewnoakes Do you think it would be safe if we migrate to .NET 6 before building the next package? #86

**Comment by drewnoakes** [comment]
> I have invited you as the collaborator of the repository and NuGet package.

Thanks! One question I have is whether you have a special process to produce the NuGet package, or whether you just pack the WinForms project.

> Do you think it would be safe if we migrate to .NET 6 before building the next package? #86

What would be the reason to migrate to .NET 6? I think it makes sense to update if you want to take advantage of features in that runtime or framework, but it does mean that users of .NET 5 would be left behind.

**Comment by jingwood** [comment]
> or whether you just pack the WinForms project.
Just pack the WinForms project. Pack two packages for each x86 and x64 platforms.
image

> What would be the reason to migrate to .NET 6? I think it makes sense to update if you want to take advantage of features in that runtime or framework, but it does mean that users of .NET 5 would be left behind.
Since the .NET 4.0 seems no longer supported and cannot be compile in VS2022, so I think whether or not to choose a LTS version like .NET 6.0, but thanks for your review, I have understand the difference.

**Comment by drewnoakes** [comment]
> Since the .NET 4.0 seems no longer supported and cannot be compile in VS2022

I can build in VS2022. I probably have a targeting pack installed. I think we can add one via PackageReference if needed, to ensure everyone can build this repo locally.

**Comment by drewnoakes** [comment]
The targeting pack NuGet package is Microsoft.NETFramework.ReferenceAssemblies. it should be added with PrivateAssets="All".

**Comment by jingwood** [comment]
Thanks. Saw this after release a new NuGet package, I will try it in the next build.

**Pull request merged**
